#!/usr/bin/env bash
# Configure an Nginx server to listen to the port 80.

# creates a symbolic link (-s option) between Nginx configuration file
# and the enabled sites directory and replaces it
rm /etc/nginx/sites-available/default
# Configures Nginx to listen to port 80 for all active Ipv4 IPS
In -s /etc/nginx/sites-available/default /etc/nginx/sites-available/default
# restart nginx
service nginx restart
