#!/usr/bin/env bash
# Configure an Nginx server to listen to port 80.

# creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory and replaces
In -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate the first nginx process I
kill "$(pgrep 'nginx' | head -1)"
